jlynn_project/jlynn/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('jlynn_project.jlynn_site.urls') ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jlynn_project/jlynn_site/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views, views_shop, purchase, order_receipt, order_summary

app_name = 'jlynn_site'


urlpatterns = [

    url(r'^$', views.homepage, name='homepage'),
    url(r'^shop/$', views_shop.art_store, name='art_store'),
    url(r'^shop/purchase/(?P<image_pk>\d+)/$', purchase.buy_painting, name='buy_painting'),
    url(r'^shop/purchase/order_summary(?P<image_pk>\d+)/$', order_summary.purchase, name='purchase'),
    url(r'^shop/order_receipt/$', order_receipt.order_receipt, name='order_receipt')

    ]

jlynn_project/jlynn_site/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.utils import timezone
import PIL
from decimal import Decimal
# Create your models here.

class Art(models.Model):
    """Database containing all relevant information for artwork."""

    title = models.CharField(max_length=200, blank=False)
    length = models.IntegerField()
    width = models.IntegerField()
    height = models.IntegerField()
    weight = models.IntegerField()
    media = models.TextField(max_length=1000, blank=False)
    status = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cost = models.DecimalField(max_digits=10, decimal_places=2)
    photo_small = models.ImageField(upload_to='images/small/', blank=True)
    photo_large= models.ImageField(upload_to='images/large/', blank=True)

class Customer(models.Model):
    """Shipping information for each Customer."""

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    street_address = models.CharField(max_length=100)
    apt_number = models.CharField(max_length=10)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=10, unique=True)

jlynn_project/jlynn_site/forms.py
from django import forms


class UserInfo(forms.Form):
    """Collects the user's name and shipping information"""

    #email_address = forms.CharField(label='Email Address', max_length=100)
    first_name = forms.CharField(label='First Name', max_length=100)
    last_name = forms.CharField(label='Last Name', max_length=100)
    street_address = forms.CharField(label='Street Address', max_length=100)
    apt_number = forms.CharField(label='Apt Number', max_length=10)
    city = forms.CharField(label='City', max_length=50)
    state = forms.CharField(label='State', max_length=20)
    zip_code = forms.CharField(label='Zipcode', max_length=5)
    phone_number = forms.CharField(label='Phone Number', max_length=20)

jlynn_project/jlynn_site/views.py
from django.shortcuts import render
from .models import Art


# Create your views here.

def homepage(request):

    collection = Art.objects.all()

    return render(request, 'home_page.html', {'collection' : collection })

jlynn_project/jlynn_site/templates/customer_form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Jlynn Arts</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  type="text/css" media="screen">
    form article label {
      display: block;
      margin: 5px;
    }

    form .submit {
      margin: 15px 0;
    }
  body {font-family: "Raleway", Arial, sans-serif}
  .w3-row img {margin-bottom: -8px}
  </style>
</head>
<body class="w3-light-grey w3-content">

  <div class="w3-light-grey w3-content" style="max-width:1500px">

      <!-- Header -->
    <header class="w3-black w3-container w3-xlarge w3-padding-24">
      <a href="{% url 'jlynn_site:homepage' %}" class="w3-text-white w3-left w3-button w3-black">MY ART</a>
      <a href="{% url 'jlynn_site:art_store' %}" class="w3-text-white w3-left w3-button w3-black">SHOP</a>
      <a href="#about" class="w3-right w3-button w3-black">About</a>
    </header>

    <br></br>

    <h3> Please enter your contact information </h3>

    {% if image_pk %}

    <div class="w3-light-grey w3-content">
    <form action="{% url 'jlynn_site:buy_painting' image_pk=image_pk%}" method="post">

      {% csrf_token %}
      <!-- {{ form.as_p }} -->

      <article>
            <label>
              <span>Amount is ${{ price }}</span>
            </label>
          </article>

          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="{{ key }}"
                  data-name="Jlynn Arts"
                  data-description="Please enter your information."
                  data-amount="{{ price_stripe }}"
                  data-locale="auto"
                  data-zip-code="true"
                  data-billing-address="true"
                  data-shipping-address="true"
                  data-allow-remember-me="false">
          </script>

    </form>
    </div>
    {% endif %}

  </div>
</body>
</html>


<!-- <form action="{% url 'jlynn_site:buy_painting' image_pk=image_pk%}" method="post">

  {% csrf_token %}
  {{ form.as_p }}

  <input class="w3-text-white w3-left w3-button w3-black" name='customer' type='submit' value='Enter'>

</form> -->

jlynn_project/jlynn_site/templates/customer_purchase.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Jlynn Arts</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  type="text/css" media="screen">
    form article label {
      display: block;
      margin: 5px;
    }

    form .submit {
      margin: 15px 0;
    }
  body {font-family: "Raleway", Arial, sans-serif}
  .w3-row img {margin-bottom: -8px}
  </style>
</head>
<body class="w3-light-grey w3-content">

  <div class="w3-light-grey w3-content" style="max-width:1500px">

      <!-- Header -->
    <header class="w3-black w3-container w3-xlarge w3-padding-24">
      <a href="{% url 'jlynn_site:homepage' %}" class="w3-text-white w3-left w3-button w3-black">MY ART</a>
      <a href="{% url 'jlynn_site:art_store' %}" class="w3-text-white w3-left w3-button w3-black">SHOP</a>
      <a href="#about" class="w3-right w3-button w3-black">About</a>
    </header>

    <br></br>

    <h3> Order Summary</h3>

    {% if image_pk %}

    <div class="w3-light-grey w3-content">
    <form action="{% url 'jlynn_site:purchase' image_pk=image_pk %}" method="post">

      {% csrf_token %}
      <article>
            <label>

              <p> {{ title }} </p>
              <br></br>
              <p>Painting is ${{ price }}</p>
              <p>Shipping is ${{ ship_price }}</p>
            </label>
          </article>

          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="{{ key }}"
                  data-name="Jlynn Arts"
                  data-description="Please enter your information."
                  data-amount="{{ total_amount }}"
                  data-locale="auto"
                  data-zip-code="false"
                  data-billing-address="true"
                  data-shipping-address="false"
                  data-allow-remember-me="false">
          </script>

    </form>
    </div>
    {% endif %}

  </div>
</body>
</html>


<!-- <form action="{% url 'jlynn_site:buy_painting' image_pk=image_pk%}" method="post">

  {% csrf_token %}
  {{ form.as_p }}

  <input class="w3-text-white w3-left w3-button w3-black" name='customer' type='submit' value='Enter'>

</form> -->

jlynn_project/jlynn_site/templates/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Jlynn Arts</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {

      width: 50%;
      margin: auto;
  }
  body {font-family: "Raleway", Arial, sans-serif}
  .w3-row img {margin-bottom: -8px}
  </style>
</head>
<body class="w3-black w3-content">

  <div class="w3-black w3-content" style="max-width:1500px">

      <!-- Header -->
    <header class="w3-black w3-container w3-xlarge w3-padding-24">
      <a href="{% url 'jlynn_site:homepage' %}" class="w3-text-white w3-left w3-button w3-black">MY ART</a>
      <a href="{% url 'jlynn_site:art_store' %}" class="w3-text-white w3-left w3-button w3-black">SHOP</a>
      <a href="#about" class="w3-right w3-button w3-black">About</a>
    </header>


    <div class="container">
      <br>
      <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval=5000>
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="w3-black carousel-inner" role="listbox">

          <div class="item active">
            <img src="media/images/small/starry_night_small.jpg" alt="Chania" width="460" height="345">
          </div>

          <div class="item">
            <img src="media/images/small/klimt_small.jpg" alt="Chania" width="460" height="345">
          </div>

        </div>

      </div>
    </div>

    <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

  </div>

  <!-- Footer / About Section -->
<footer class="w3-black w3-padding-64 w3-center" id="about">
  <h2>About</h2>
  <img src="/w3images/boy.jpg" class="w3-image w3-padding-32" width="300" height="300">
  <form style="margin:auto;width:60%" action="/action_page.php" target="_blank">
    <p>Just me, myself and I, exploring the universe of unknownment. I have a heart of love and an interest of lorem ipsum and mauris neque quam blog. I want to share my world with you. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
    <p class="w3-large w3-text-pink">Do not hesitate to contact me!</p>
    <div class="w3-section">
      <label><b>Name</b></label>
      <input class="w3-input w3-border" type="text" required name="Name">
    </div>
    <div class="w3-section">
      <label><b>Email</b></label>
      <input class="w3-input w3-border" type="text" required name="Email">
    </div>
    <div class="w3-section">
      <label><b>Message</b></label>
      <input class="w3-input w3-border" required name="Message">
    </div>
    <button type="submit" class="w3-button w3-block w3-dark-grey">Send</button>
  </form>
  <br>
  <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank" class="w3-hover-text-green">w3.css</a></p>
</footer>

</body>
</html>

jlynn_project/jlynn_site/templates/order_receipt.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Jlynn Arts</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  body {font-family: "Raleway", Arial, sans-serif}
  .w3-row img {margin-bottom: -8px}
  </style>
</head>
<body class="w3-black w3-content">

  <div class="w3-black w3-content" style="max-width:1500px">

      <!-- Header -->
    <header class="w3-black w3-container w3-xlarge w3-padding-24">
      <a href="{% url 'jlynn_site:homepage' %}" class="w3-text-white w3-left w3-button w3-black">MY ART</a>
      <a href="{% url 'jlynn_site:art_store' %}" class="w3-text-white w3-left w3-button w3-black">SHOP</a>
      <a href="#about" class="w3-right w3-button w3-black">About</a>
    </header>

    <div class="w3-light-grey w3-content">


      <p> Thank you, your order has been processed. We sincerly hope you enjoy your piece.</p>

      <h4> Order Summary</h4>
      <br></br>
      <p> {{ title }} </p>
      <strong> ${{ price }} </strong>

    </div>

  </div>
</body>
</html>

jlynn_project/jlynn_site/templates/order_summary.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Jlynn Arts</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  body {font-family: "Raleway", Arial, sans-serif}
  .w3-row img {margin-bottom: -8px}
  </style>
</head>
<body class="w3-black w3-content">

  <div class="w3-black w3-content" style="max-width:1500px">

      <!-- Header -->
    <header class="w3-black w3-container w3-xlarge w3-padding-24">
      <a href="{% url 'jlynn_site:homepage' %}" class="w3-text-white w3-left w3-button w3-black">MY ART</a>
      <a href="{% url 'jlynn_site:art_store' %}" class="w3-text-white w3-left w3-button w3-black">SHOP</a>
      <a href="#about" class="w3-right w3-button w3-black">About</a>
    </header>

    <div class="w3-light-grey w3-content">


      <p> Thank you, your order has been processed. We sincerly hope you enjoy your piece.</p>

      <h4> Order Summary</h4>
      <br></br>
      <p> {{ title }} </p>
      <strong> ${{ price }} </strong>

    </div>

  </div>
</body>
</html>

jlynn_project/jlynn_site/templates/store_page.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Jlynn Arts</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  body {font-family: "Raleway", Arial, sans-serif}
  .w3-row img {margin-bottom: -8px}
  </style>
</head>

<body class="w3-black w3-content">

  <div class="w3-black w3-content" style="max-width:1500px">

      <!-- Header -->
    <header class="w3-black w3-container w3-xlarge w3-padding-24">
      <a href="{% url 'jlynn_site:homepage' %}" class="w3-text-white w3-left w3-button w3-black">MY ART</a>
      <a href="{% url 'jlynn_site:art_store' %}" class="w3-text-white w3-left w3-button w3-black">SHOP</a>
      <a href="#about" class="w3-right w3-button w3-black">About</a>
    </header>

  <!-- Product grid -->
  <h3>Some of my Work</h3><br>


  <div class="container-fluid bg-3 text-center">
    <div class="row">

      {% for image in collection %}
      <div class="col-sm-3">
        <p>{{ image.title }}</p>

        <img src="{{MEDIA_URL}}{{image.photo_large.url}}" class="img-responsive" style="width:100%" alt="Image">

        <p> {{ image.media }}<p>
        <p> {{ image.length }} X {{ image.width }}<p>
        <p> {{ image.price }}<p>
        <div class="container-fluid bg-3 text-center">

        <form action="{% url 'jlynn_site:buy_painting' image_pk=image.id %}" method="post">

          {% csrf_token %}

          <input class="w3-text-white w3-left w3-button w3-black" name='buy' type='submit' value='Buy'>

        </form>
      </div>

      </div>
      {% endfor %}
    </div>
  </div>

  </div>

</body>
</html>